import PDFDocument from 'pdfkit';
import { ICustomer } from '../models/Customer';
import { ITransaction } from '../models/Transaction';
import { IUser } from '../models/User';
import { IInvoice } from '../models/Invoice';

function formatDate(date: Date): string {
  return new Date(date).toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });
}

function formatAmount(amount: number): string {
  return `₹${amount.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`;
}

export async function generateCustomerStatement(
  merchant: IUser,
  customer: ICustomer,
  transactions: ITransaction[],
  dateFrom?: Date,
  dateTo?: Date
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header
    doc.fontSize(22).fillColor('#6366f1').text('UdhaariBook', 50, 50);
    doc.fontSize(10).fillColor('#6b7280').text('Digital Khata Management', 50, 76);

    doc.moveTo(50, 95).lineTo(545, 95).strokeColor('#e5e7eb').lineWidth(1).stroke();

    // Business info
    doc.fontSize(14).fillColor('#1f2937').text(merchant.businessName, 50, 110);
    doc.fontSize(10).fillColor('#6b7280');
    doc.text(`Owner: ${merchant.ownerName}`, 50, 128);
    if (merchant.phone) doc.text(`Phone: ${merchant.phone}`, 50, 142);
    doc.text(`Email: ${merchant.email}`, 50, merchant.phone ? 156 : 142);

    // Customer info
    doc.fontSize(12).fillColor('#1f2937').text('Customer Statement', 350, 110);
    doc.fontSize(10).fillColor('#6b7280');
    doc.text(`Name: ${customer.name}`, 350, 128);
    if (customer.phone) doc.text(`Phone: ${customer.phone}`, 350, 142);
    const periodText = dateFrom && dateTo
      ? `Period: ${formatDate(dateFrom)} – ${formatDate(dateTo)}`
      : dateFrom ? `From: ${formatDate(dateFrom)}`
      : dateTo ? `Until: ${formatDate(dateTo)}`
      : `Generated: ${formatDate(new Date())}`;
    doc.text(periodText, 350, customer.phone ? 156 : 142);

    // Outstanding
    const outstandingY = 190;
    doc.rect(50, outstandingY, 495, 50).fillColor('#fef3c7').fill();
    doc.fontSize(11).fillColor('#92400e').text('Total Outstanding Balance', 60, outstandingY + 8);
    const outColor = customer.totalOutstanding > 0 ? '#dc2626' : '#16a34a';
    doc.fontSize(18).fillColor(outColor).text(
      formatAmount(Math.abs(customer.totalOutstanding)),
      60,
      outstandingY + 22
    );
    const label = customer.totalOutstanding > 0 ? '(Customer owes you)' : '(You owe customer)';
    doc.fontSize(9).fillColor('#6b7280').text(label, 180, outstandingY + 28);

    // Table header
    const tableY = 260;
    doc.rect(50, tableY, 495, 24).fillColor('#6366f1').fill();
    doc.fontSize(10).fillColor('#ffffff');
    doc.text('Date', 60, tableY + 7);
    doc.text('Type', 180, tableY + 7);
    doc.text('Amount', 280, tableY + 7);
    doc.text('Note', 370, tableY + 7);

    // Table rows
    let rowY = tableY + 24;
    transactions.forEach((tx, i) => {
      const bg = i % 2 === 0 ? '#f9fafb' : '#ffffff';
      doc.rect(50, rowY, 495, 22).fillColor(bg).fill();

      doc.fontSize(9).fillColor('#374151');
      doc.text(formatDate(tx.createdAt), 60, rowY + 6);
      doc.fillColor(tx.type === 'gave' ? '#dc2626' : '#16a34a');
      doc.text(tx.type === 'gave' ? 'You Gave' : 'You Got', 180, rowY + 6);
      doc.fillColor('#374151');
      doc.text(formatAmount(tx.amount), 280, rowY + 6);
      doc.text(tx.note ?? '-', 370, rowY + 6, { width: 165, ellipsis: true });

      rowY += 22;
      if (rowY > 750) {
        doc.addPage();
        rowY = 50;
      }
    });

    // Footer
    doc.moveTo(50, rowY + 10).lineTo(545, rowY + 10).strokeColor('#e5e7eb').stroke();
    doc.fontSize(8).fillColor('#9ca3af').text(
      'Generated by UdhaariBook — Your digital khata, always with you.',
      50,
      rowY + 20,
      { align: 'center', width: 495 }
    );

    doc.end();
  });
}

export async function generateBusinessSummary(
  merchant: IUser,
  customers: ICustomer[],
  dateFrom?: Date,
  dateTo?: Date
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header
    doc.fontSize(22).fillColor('#6366f1').text('UdhaariBook', 50, 50);
    doc.fontSize(16).fillColor('#1f2937').text('Business Summary Report', 50, 80);
    const periodLine = dateFrom && dateTo
      ? `${merchant.businessName} — ${formatDate(dateFrom)} to ${formatDate(dateTo)}`
      : `${merchant.businessName} — ${formatDate(new Date())}`;
    doc.fontSize(10).fillColor('#6b7280').text(periodLine, 50, 100);

    doc.moveTo(50, 118).lineTo(545, 118).strokeColor('#e5e7eb').stroke();

    // Summary stats
    const totalOutstanding = customers.reduce((s, c) => s + Math.max(0, c.totalOutstanding), 0);
    const customersWithDues = customers.filter((c) => c.totalOutstanding > 0).length;

    const statsY = 135;
    // Box 1
    doc.rect(50, statsY, 150, 60).fillColor('#fef2f2').fill();
    doc.fontSize(10).fillColor('#dc2626').text('Total Receivable', 60, statsY + 8);
    doc.fontSize(16).fillColor('#dc2626').text(formatAmount(totalOutstanding), 60, statsY + 26);

    // Box 2
    doc.rect(215, statsY, 150, 60).fillColor('#f0fdf4').fill();
    doc.fontSize(10).fillColor('#16a34a').text('Customers with Dues', 225, statsY + 8);
    doc.fontSize(16).fillColor('#16a34a').text(String(customersWithDues), 225, statsY + 26);

    // Box 3
    doc.rect(380, statsY, 165, 60).fillColor('#eff6ff').fill();
    doc.fontSize(10).fillColor('#2563eb').text('Total Customers', 390, statsY + 8);
    doc.fontSize(16).fillColor('#2563eb').text(String(customers.length), 390, statsY + 26);

    // Table
    const tableY = 220;
    doc.rect(50, tableY, 495, 24).fillColor('#6366f1').fill();
    doc.fontSize(10).fillColor('#ffffff');
    doc.text('Customer', 60, tableY + 7);
    doc.text('Phone', 220, tableY + 7);
    doc.text('Outstanding', 340, tableY + 7);
    doc.text('Last Transaction', 430, tableY + 7);

    const sorted = [...customers].sort((a, b) => b.totalOutstanding - a.totalOutstanding);
    let rowY = tableY + 24;

    sorted.forEach((c, i) => {
      const bg = i % 2 === 0 ? '#f9fafb' : '#ffffff';
      doc.rect(50, rowY, 495, 22).fillColor(bg).fill();
      doc.fontSize(9).fillColor('#374151');
      doc.text(c.name, 60, rowY + 6, { width: 150, ellipsis: true });
      doc.text(c.phone ?? '-', 220, rowY + 6);
      doc.fillColor(c.totalOutstanding > 0 ? '#dc2626' : '#16a34a');
      doc.text(formatAmount(c.totalOutstanding), 340, rowY + 6);
      doc.fillColor('#6b7280');
      doc.text(c.lastTransactionAt ? formatDate(c.lastTransactionAt) : '-', 430, rowY + 6);
      rowY += 22;
      if (rowY > 750) { doc.addPage(); rowY = 50; }
    });

    doc.moveTo(50, rowY + 10).lineTo(545, rowY + 10).strokeColor('#e5e7eb').stroke();
    doc.fontSize(8).fillColor('#9ca3af').text(
      'Generated by UdhaariBook — Your digital khata, always with you.',
      50, rowY + 20, { align: 'center', width: 495 }
    );

    doc.end();
  });
}

export async function generateInvoicePdf(
  merchant: IUser,
  invoice: IInvoice
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const BRAND = '#6366f1';
    // Guard: customerId may be an ObjectId if populate failed (e.g. deleted customer)
    const rawCustomer = invoice.customerId as unknown as { name?: string; phone?: string; email?: string } | null;
    const customer = {
      name: rawCustomer?.name ?? 'Unknown Customer',
      phone: rawCustomer?.phone,
      email: rawCustomer?.email,
    };

    // ── Header band ─────────────────────────────────────────────────────────
    doc.rect(0, 0, 595, 90).fillColor(BRAND).fill();

    // Left: merchant info
    doc.fontSize(16).fillColor('#ffffff').text(merchant.businessName, 50, 20, { width: 280 });
    doc.fontSize(9).fillColor('rgba(255,255,255,0.8)');
    if (merchant.ownerName) doc.text(merchant.ownerName, 50, 40);
    if (merchant.phone) doc.text(merchant.phone, 50, 53);
    if (merchant.gstNumber) doc.text(`GSTIN: ${merchant.gstNumber}`, 50, 66);

    // Right: INVOICE label + number
    doc.fontSize(11).fillColor('rgba(255,255,255,0.7)').text('INVOICE', 370, 20, { width: 175, align: 'right' });
    doc.fontSize(18).fillColor('#ffffff').text(invoice.invoiceNumber, 370, 34, { width: 175, align: 'right' });
    doc.fontSize(9).fillColor('rgba(255,255,255,0.8)');
    doc.text(`Date: ${formatDate(invoice.createdAt)}`, 370, 58, { width: 175, align: 'right' });
    if (invoice.dueDate) {
      doc.text(`Due: ${formatDate(invoice.dueDate)}`, 370, 71, { width: 175, align: 'right' });
    }

    // ── Bill To ──────────────────────────────────────────────────────────────
    const billY = 110;
    doc.fontSize(8).fillColor('#9ca3af').text('BILL TO', 50, billY);
    doc.fontSize(13).fillColor('#1f2937').text(customer.name, 50, billY + 12);
    doc.fontSize(10).fillColor('#6b7280');
    if (customer.phone) doc.text(customer.phone, 50, billY + 28);
    if (customer.email) doc.text(customer.email, 50, customer.phone ? billY + 41 : billY + 28);

    // Status badge
    const statusColors: Record<string, { bg: string; text: string }> = {
      paid: { bg: '#d1fae5', text: '#065f46' },
      unpaid: { bg: '#fef3c7', text: '#92400e' },
      cancelled: { bg: '#f3f4f6', text: '#6b7280' },
    };
    const sc = statusColors[invoice.status] ?? statusColors.unpaid;
    const statusLabel = invoice.status.toUpperCase();
    doc.rect(400, billY + 10, 145, 26).fillColor(sc.bg).fill();
    doc.fontSize(11).fillColor(sc.text).text(statusLabel, 400, billY + 17, { width: 145, align: 'center' });

    // ── Items table ──────────────────────────────────────────────────────────
    const tableY = billY + 70;
    doc.rect(50, tableY, 495, 22).fillColor(BRAND).fill();
    doc.fontSize(9).fillColor('#ffffff');
    doc.text('#', 55, tableY + 6, { width: 20 });
    doc.text('Item', 80, tableY + 6, { width: 180 });
    doc.text('Unit', 265, tableY + 6, { width: 55 });
    doc.text('Qty', 325, tableY + 6, { width: 45 });
    doc.text('Unit Price', 375, tableY + 6, { width: 80 });
    doc.text('Total', 460, tableY + 6, { width: 80, align: 'right' });

    let rowY = tableY + 22;
    invoice.items.forEach((item, i) => {
      const bg = i % 2 === 0 ? '#f9fafb' : '#ffffff';
      doc.rect(50, rowY, 495, 22).fillColor(bg).fill();
      doc.fontSize(9).fillColor('#374151');
      doc.text(String(i + 1), 55, rowY + 6, { width: 20 });
      doc.text(item.productName, 80, rowY + 6, { width: 180, ellipsis: true });
      doc.text(item.unit, 265, rowY + 6, { width: 55 });
      doc.text(String(item.quantity), 325, rowY + 6, { width: 45 });
      doc.text(formatAmount(item.unitPrice), 375, rowY + 6, { width: 80 });
      doc.text(formatAmount(item.total), 460, rowY + 6, { width: 80, align: 'right' });
      rowY += 22;
    });

    // ── Totals ───────────────────────────────────────────────────────────────
    rowY += 8;
    const totalsX = 360;
    const valX = 460;
    const valW = 80;

    doc.moveTo(totalsX, rowY).lineTo(545, rowY).strokeColor('#e5e7eb').lineWidth(1).stroke();
    rowY += 8;

    doc.fontSize(10).fillColor('#6b7280').text('Subtotal', totalsX, rowY, { width: 95 });
    doc.text(formatAmount(invoice.subtotal), valX, rowY, { width: valW, align: 'right' });
    rowY += 18;

    if (invoice.gstPercent && invoice.gstAmount) {
      doc.text(`GST (${invoice.gstPercent}%)`, totalsX, rowY, { width: 95 });
      doc.text(formatAmount(invoice.gstAmount), valX, rowY, { width: valW, align: 'right' });
      rowY += 18;
    }

    doc.moveTo(totalsX, rowY).lineTo(545, rowY).strokeColor('#e5e7eb').stroke();
    rowY += 8;
    doc.fontSize(12).fillColor('#1f2937').font('Helvetica-Bold').text('Total', totalsX, rowY, { width: 95 });
    doc.text(formatAmount(invoice.totalAmount), valX, rowY, { width: valW, align: 'right' });
    doc.font('Helvetica');

    if (invoice.note) {
      rowY += 30;
      doc.fontSize(9).fillColor('#9ca3af').text('Note:', 50, rowY);
      doc.fillColor('#374151').text(invoice.note, 50, rowY + 12, { width: 300 });
    }

    // ── Footer ───────────────────────────────────────────────────────────────
    doc.fontSize(8).fillColor('#9ca3af').text(
      'Generated by UdhaariBook — Your digital khata, always with you.',
      50,
      780,
      { align: 'center', width: 495 }
    );

    doc.end();
  });
}
